### ISSUE TITLE
Filtering by groups_base in getGroupsForPrincipal should be case-insensitive

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/Products.LDAPMultiPlugins#5]
`getGroupsForPrincipal()` currently filters down returned groups in a case-sensitive way:
https://github.com/4teamwork/Products.LDAPMultiPlugins/blob/7a1fc0f952da8ab2247883d79fa90b
5e6243da14/Products/LDAPMultiPlugins/ActiveDirectoryMultiPlugin.py#L236

This check should probably be case-insensitive.

**Comment by buchi** [comment]
Fixed with https://github.com/4teamwork/Products.LDAPMultiPlugins/pull/7
